### ISSUE TITLE
How do I actually use it?

### ISSUE THREAD

**Issue by igor9silva** [homerours/cordova-music-controls-plugin#10]
Hi,

I'm developing a music app with cordova.
The question may seem stupid but I can't figure out how to make it work.

I've tried this:
```
ionic start myapp
cd myapp
cordova plugin add https://github.com/homerours/cordova-music-controls-plugin
```

Then I created a button and linked it to a function which does ```.create()``` ```.subscribe()``` and ```listen()``` at the ```MusicControls``` variable. I've inspected it using chrome and ```MusicControls``` is correctly populated. The button click function is being called as well.

When the button is clicked it shows nothing.
I've tried searching for bugs at the plugin source code, both the JS interface and the Java code seem ok to me.

Can you help me?
Thanks in advance

**Comment by homerours** [comment]
Hi!
Sorry, I think there were an error in the plugin.XML, I fixed it. 
Can you remove remove the plugin:
`cordova plugin rm com.homerours.musiccontrols`
And reinstall it from github? I hope it will fix it ;)
I'm also developping a music app with cordova [here](https://github.com/homerours/cosmic) it might be intersting for you !

**Comment by igor9silva** [comment]
Thanks for your answer @homerours and sorry for the delay. I'll give it try tomorrow and update here.

**Comment by igor9silva** [comment]
Working like a charm!
