### ISSUE TITLE
Android icons not showing up right

### ISSUE THREAD

**Issue by hoboman313** [homerours/cordova-music-controls-plugin#111]
Has anyone got them to work well with this lib?

I went through multiple .PNG media icon sets converting them to drawables using some online generators. Added their references to the cordova's config.xml and configured the lib with the names, but each time the icons ended up looking completely garbled(can't make the icons out at all) on my physical devices. Only the notification item looked somewhat decent except when I pull down the status bar, its color does not inverse correctly. Am I missing something here? Do these have to be .SVG drawables? I'm curious how you guys (@BuddyLReno @darthdie) got yours to work well.

**Comment by shawns582** [comment]
@hoboman313 did you figure this out?
