### ISSUE TITLE
Doesn't work on certain Android versions

### ISSUE THREAD

**Issue by frissonlabs** [homerours/cordova-music-controls-plugin#114]
I'm also getting the same behavior, except I'm using Ionic v1. It doesn't work on the following devices:

-Google Pixel 2 running Android 8.1.0
-LG G Pad X running Android 7.0
-Samsung Galaxy Note II running Android 4.4.2

However, it works on a cheap ZTE phone running Android 5.1.1.

Here's the demo project I created to test across on these devices:
https://github.com/frissonlabs/Android-Music-Controls-Test

**Comment by RightCapital** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ashishmehra@gmail.com
    Domain rightcapital.co.uk has exceeded the max emails per hour (59/50 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o9.sgmail.github.com ([167.89.101.2]:56083)
	by mercury.speedyservers.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89_1)
	(envelope-from <bounces+848413-2999-ashish=rightcapital.co.uk@sgmail.github.com>)
	id 1egIaE-002Jki-MG
	for ashish@rightcapital.co.uk; Mon, 29 Jan 2018 23:11:26 +0000
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=GFP8tF7BXpRKSqJtj75NLtVmbCM=; b=H8+xDzsQeFEEbELv
	ZvQMfA2zjldrOo354rBzmkr/lUobsNVTUuSrnrwzACOAYpC2Zic1Poewpd6FvxJM
	V4YRQagAnK3u6Ei+kbTHzuCfOCDG3TF8MKHH6GM33q9daTHaP5jcCrfFBX0Mg6sk
	g7bGtSsgVqB0tya1jOQD7raKOos=
Received: by filter0357p1las1.sendgrid.net with SMTP id filter0357p1las1-11445-5A6FAA1B-26
        2018-01-29 23:11:23.392789623 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id 9eVodFwzRJ2eY8emAfyK_w
	for <ashish@rightcapital.co.uk>; Mon, 29 Jan 2018 23:11:23.207 +0000 (UTC)
Date: Mon, 29 Jan 2018 23:11:24 +0000 (UTC)

**Comment by shawns582** [comment]
@frissonlabs did you solve this problem? I am having the same issue on a Google Pixel 2 on Ionic 3 (although it was previously working)

**Comment by shawns582** [comment]
checking in on this again. Did you ever get this working on a Pixel 2?

**Comment by frissonlabs** [comment]
Yes, and I didn't have to do anything else extra

On Feb 19, 2018 4:34 PM, "shawns582" <notifications@github.com> wrote:

checking in on this again. Did you ever get this working on a Pixel 2?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/homerours/cordova-music-controls-plugin/issues/114#issuecomment-366834669>,
or mute the thread

**Comment by shawns582** [comment]
@frissonlabs thanks, that's weird..it just started working? I hope I have that kind of luck!
