### ISSUE TITLE
Does not support android api 26

### ISSUE THREAD

**Issue by amitkhare** [homerours/cordova-music-controls-plugin#119]
Does not support android api 26.

**Comment by amitkhare** [comment]
fixed it. how to submit a pull request?

**Comment by malek75** [comment]
Hello, Can you submit your solution please ?

**Comment by amitkhare** [comment]
# visit :
 https://github.com/amitkhare/cordova-music-controls-plugin/blob/master/src/android/MusicControlsNotification.java

# Replace all the content in

> CORDOVA_PROJECT_ROOT\plugins\cordova-plugin-music-controls\src\android\MusicControlsNotification.java

# Then in terminal:
`$ cordova platform remove android `
`$ cordova platform add android`

`$ cordova run android`

**Comment by malek75** [comment]
It's working well again! 
Thank you very much @amitkhare

**Comment by phiamo** [comment]
+1 can we create a merge request out of this ?

**Comment by kgroat** [comment]
looks like the PR #120 has been merged, fixing this issue, now it just needs to be published to npm

**Comment by amitkhare** [comment]
Looks like issue resolved.
