### ISSUE TITLE
Can not create music control in android version 8 or above

### ISSUE THREAD

**Issue by amanpatel1449** [homerours/cordova-music-controls-plugin#125]
My android version is 8.0.0 and i have use Honor 9 Lite device in this device can't create music control. In lower version of android works fine. Thanks in advance. Please help me to out here.

**Comment by DiegoZurita** [comment]
+1

**Comment by ramoncarreras** [comment]
This issue is related to:
https://github.com/homerours/cordova-music-controls-plugin/issues/101

**Comment by sinedied** [comment]
Use latest version from github master, not npm and it works.

**Comment by amanpatel1449** [comment]
@neoassyrian

**Comment by amanpatel1449** [comment]
@neoassyrian 
Thank you for your solution in #101 is work in android 8.0.0.
Now it's work fine.
You are great.

**Comment by amanpatel1449** [comment]
@neoassyrian
Thank you for your solution in #101 is work in android 8.0.0.
Now it's work fine.
You are great.
