### ISSUE TITLE
iOS not showing Now Playing Information

### ISSUE THREAD

**Issue by walalm** [homerours/cordova-music-controls-plugin#128]
On iOS the information about the current playing audio doesn't show. It only shows the Url of the media and the play/pause button.

**Comment by area809** [comment]
make sure you change your audio provider to CordovaMediaProvider in the ionic-audio.module

**Comment by walalm** [comment]
@area809  yep, found the issue, it was actually loading the WebProvider... changed it properly to use the CordovaMediaProvider and now it is working as expected. Thank you

**Comment by shawns582** [comment]
@area809 @walalm  sorry can one of you tell me how to change the audio provider? I am having the same issue. I am currently using the html5 audio player to play audio in my ionic app, do I need to change to cordova-plugin-media? Or is this just a setting change somewhere? Thanks!

**Comment by walalm** [comment]
> @area809 @walalm sorry can one of you tell me how to change the audio provider? I am having the same issue. I am currently using the html5 audio player to play audio in my ionic app, do I need to change to cordova-plugin-media? Or is this just a setting change somewhere? Thanks!

Change it to use the cordova plugin media

**Comment by shawns582** [comment]
Cool thanks, will try that!
