### ISSUE TITLE
case 'music-controls-play': don't work

### ISSUE THREAD

**Issue by freeweed** [homerours/cordova-music-controls-plugin#13]
every case work find just case 'music-controls-play': it's don't work can you tell me why? this is my function
function events(action) {
      switch(action) {
          case 'music-controls-next':
              $scope.skip();
              break;
          case 'music-controls-previous':
              $scope.back();
              break;
          case 'music-controls-pause':
              $scope.stop();
              break;
          case 'music-controls-play':
              console.log("play click");
              $scope.playMedia(playing); 
              break;
          default:
              break;
      }
    }
play click don't show
sorry for my English :"(

**Comment by homerours** [comment]
Did you submit again: `MusicControls.create(..., isPlaying: 'false',...)` after you listened to the "pause" event? It should replace the pause button with the play button and allow you to use the "play" event.

**Comment by freeweed** [comment]
No this is my $scope.stop()
$scope.stop = function(){
    $scope.musics[playing].isPlay = false;
    $scope.isPlaying = false;
    media.pause();
  }

**Comment by homerours** [comment]
So, you have to update the notification in the stop function. Add 
`MusicControls.create({ ..., isPlaying : false, ...})` to your function ( "..." should be the same infos that you submitted before, if the track has not changed). You should also do the same in your play function, in order to show the "pause" button.
