### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by preterive** [homerours/cordova-music-controls-plugin#139]
$ cordova plugin add cordova-plugin-music-controls
(node:25011) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin git+https://github.com/homerours/cordova-music-controls-plugin.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:37
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:112:11)
(node:25011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25011) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by owen-mills** [comment]
Use phonegap or another framework on top of Cordova. Simply using Cordova will not allow you to add most plugins.

**Comment by preterive** [comment]
but why i have to use phonegap for a cordova plugin?

**Comment by owen-mills** [comment]
Because Cordova is a piece of crap so they had to design Phonegap on top of it to make it better. You still use Phonegap to get cordova plugins.
