### ISSUE TITLE
Cover image is being reloaded every time create() is called

### ISSUE THREAD

**Issue by igor9silva** [homerours/cordova-music-controls-plugin#14]
What do you think about caching the cover image?
I'm loading images from other server and it takes too much time to Create() terminate. When changing the music it's ok, since there is new data, but it's pretty dumb to re-download the image everytime user play/pause music.

Maybe creating a method 'tooglePlay()', which would recreate the notification using the same info just toggling the isPlaying would be a better approach.

I want to create a pull request for data, but I don't know when I'll have available time. Maybe this Sunday I'll do that.

Let me know what you think about so we can work on it.

**Comment by homerours** [comment]
Hi
Both are great ideas !
About the tooglePlay fonction, I wanted to add it last week (and do some code refractoring) but I got some issues with my Cordova Cli... 
You are welcome to create à pull request if you have time to do this. If not, I 'll do it as soon as m'y Cordova gets better ;)

**Comment by homerours** [comment]
I added the toggle play/pause function: 3d70108d90

**Comment by igor9silva** [comment]
Thanks @homerours, will check it today.

**Comment by igor9silva** [comment]
@homerours 
The UpdateIsPlaying method was calling createbuilder() again, which would download the cover and create the whole notification again.
I've created a pull request to fix it, please check it out.
