### ISSUE TITLE
Run in Background

### ISSUE THREAD

**Issue by preterive** [homerours/cordova-music-controls-plugin#149]
Please add a function to use the App with this Plugin: https://github.com/katzer/cordova-plugin-background-mode
without make a second notification.

**Comment by rastographics** [comment]
I'm trying to figure out how to do this too...there does not seem to be any plugin yet that can do music controls and and also play in background

**Comment by paulovargatt** [comment]
I made an implementation when loading a media I enabled the background mode and called the method for music controls ...
```
this.api.getMasterMedia().subscriptions.loadedData.subscribe(() => {
            if (this.platform.is('cordova')) {
                this.backgroundMode.enable();
                this.backgroundMode.setDefaults({
                    title: 'Em execução',
                    text: '',
                    silent: true
                });

                this.backgroundMode.on('activate').subscribe(() => {
                    this.backgroundMode.disableWebViewOptimizations();
                });
            }
            setTimeout(() => {
                this.enableMusicControl();
            }, 100);
        });
```

**Comment by rastographics** [comment]
@paulovargatt it looks like you are using these plugins through ionic native? if so, what version of ionic are you using?

**Comment by paulovargatt** [comment]
ionic 4.0.2

**Comment by rastographics** [comment]
Do you get any errors when generating Android production apk? If not,
please what command are you using?

**Comment by preterive** [comment]
> 
> 
> I made an implementation when loading a media I enabled the background mode and called the method for music controls ...
> 
> ```
> this.api.getMasterMedia().subscriptions.loadedData.subscribe(() => {
>             if (this.platform.is('cordova')) {
>                 this.backgroundMode.enable();
>                 this.backgroundMode.setDefaults({
>                     title: 'Em execução',
>                     text: '',
>                     silent: true
>                 });
> 
>                 this.backgroundMode.on('activate').subscribe(() => {
>                     this.backgroundMode.disableWebViewOptimizations();
>                 });
>             }
>             setTimeout(() => {
>                 this.enableMusicControl();
>             }, 100);
>         });
> ```

But this made a second notification, not?

**Comment by tobika** [comment]
For the cordova-background-plugin you can add a config `silent: true` which disables the notification. But I'm not sure that it keeps working or that the notification from the music controls keep the app alive.

**Comment by ghenry22** [comment]
If you use the notification from this plugin (which gives you remote controls and serves the purpose of having a notification tied to the background task) you can just set silent mode on the background-mode plugin so it doesn't show any notification.

**Comment by preterive** [comment]
This didn't works too.
The music controls plugin is simple too old and still use the old notify and not the startForegroundService methods.

**Comment by pvandrunen** [comment]
Maybe this is my problem as well? I cannot get this plugin to work on iOS. I have the background mode plugin installed. I have an ionic v1 project that I made several years ago that works, but when I try to build it now the lock screen controls have stopped working.

**Comment by bergergit** [comment]
This is working for me
I'm using https://github.com/apache/cordova-plugin-media to play music in the background.
Then, I use the callback methods of cordova-music-controls-plugin to play/pause the music. (I'm just playing a single music).
Tested on iOS 12.2

**Comment by a-tesh** [comment]
HI all:

This plugin does not seem run in the background without additional plugins. A lot of people have had success combining this plugin with the Background Mode plugin which I believe may work for anything less than Android 8. 

Anything targeting API 26 or higher requires that the plugin runs as a foreground service and as such has a persistent notification icon: [https://developer.android.com/guide/components/services](url).

The way which has recently 'worked' for me is combining this Music Controls Plugin with a foreground service plugin: [https://www.npmjs.com/package/cordova-plugin-foreground-service](url). Although with this method two icons are displayed, one for the foreground service and the other for the media controls.

I'm currently looking into the possibility of extending the MusicControlsNotification as a service but my Java experience is limited.

**Comment by preterive** [comment]
:)
I already extended it, but there are still a few errors. I upload it if I'm done.

**Comment by webbkvalite** [comment]
I think this plugin needs to implement  AVQueuePlayer for it to work in iOS locked mode, if you want continuous GUI updates and playlist support. 
See this one for reference: https://www.npmjs.com/package/cordova-plugin-playlist
...which unfortunately doesn't support Ionic4 / cordova 9.

**Comment by preterive** [comment]
Simple use this fork: https://github.com/preterive/cordova-music-controls-plugin
