### ISSUE TITLE
MusicControls.create is undefined

### ISSUE THREAD

**Issue by Whebcraft** [homerours/cordova-music-controls-plugin#17]
MusicControls is called  in a function 
function playmusic(){
 try {
MusicControls.create({
    track : 'My track',
    artist : 'my subttile',
    cover : 'img/Musical Notes-100.png',
    isPlaying : true,
    ticker : 'Now playing ......'
}, onSuccess, onError); 
 }catch(e){
        console(e.message);
 }
}
console(e.message); Returns MusicControls.create is undefined please how do I solve this?

**Comment by homerours** [comment]
I don't have any particular idea:
- try to remove the plugin (`cordova plugin rm cordova-plugin-music-controls`) and install it again.
- are you working on android?

**Comment by Whebcraft** [comment]
yes

**Comment by malek75** [comment]
I have the same issue. Have you find the solution ? thanks !

**Comment by filfat** [comment]
I assume this happens on iOS,
You need to feature detect to make sure you're not trying to call the plugin on unsupported platforms.

**Comment by malek75** [comment]
No the problem happen on Android :/

**Comment by gowchow** [comment]
I have the same problem. MusicControls.create is not working for me on android 6.0.1 ( nexus6)
homerorus, could you please help us.

**Comment by Yusadolat** [comment]
@Whebcraft Have you resolved this issue?

**Comment by johnraftery** [comment]
What was the solution to this? I am having the same issue

**Comment by baalpeteor** [comment]
also having issue. i uninstalled, reinstalled "npm i cordova-plugin-music-controls" from my project folder, it adds it to the project, but in the project i do this:

`
StartJS
MusicControls.create({
    track       : 'The Peoples Station',		// optional, default : ''
    artist      : '927 FM',						// optional, default : ''
    album       : '',     // optional, default: ''
 	  cover       : 'kz.png',		// optional, default : nothing
    // cover can be a local path (use fullpath 'file:///storage/emulated/...', or only 'my_image.jpg' if my_image.jpg is in the www folder of your app)
    //			 or a remote url ('http://...', 'https://...', 'ftp://...')
    isPlaying   : true,							// optional, default : true
    dismissable : true,							// optional, default : false

    // hide previous/next/close buttons:
    hasPrev   : false,		// show previous button, optional, default: true
    hasNext   : false,		// show next button, optional, default: true
    hasClose  : true,		// show close button, optional, default: false

    // iOS only, optional

    duration : 60, // optional, default: 0
    elapsed : 10, // optional, default: 0
  	hasSkipForward : false, //optional, default: false. true value overrides hasNext.
  	hasSkipBackward : false, //optional, default: false. true value overrides hasPrev.
  	skipForwardInterval : 15, //optional. default: 0.
    skipBackwardInterval : 15, //optional. default: 0.
    hasScrubbing : false, //optional. default to false. Enable scrubbing from control center progress bar

    // Android only, optional
    // text displayed in the status bar when the notification (and the ticker) are updated
    ticker	  : 'Now playing "The Peoples Station!',
    //All icons default to their built-in android equivalents
    //The supplied drawable name, e.g. 'media_play', is the name of a drawable found under android/res/drawable* folders
    playIcon: 'media_play',
    pauseIcon: 'media_pause',
    prevIcon: 'media_prev',
    nextIcon: 'media_next',
    closeIcon: 'media_close',
    notificationIcon: 'notification'
}, onSuccess, onError);
endJS`

and it comes back with:
Error: "'MusicControls' is undefined" - Line: 353 - Char: 13 - Code: 0 - Url: http://127.0.0.1:9999/app/scripts/app.js

when i build & run in my environment. (ps it successfully took "npm i cordova-plugin-music-controls" and "npm list" shows it at the end of the project i'm working on)
