### ISSUE TITLE
[Android] Small close button

### ISSUE THREAD

**Issue by lesonunique** [homerours/cordova-music-controls-plugin#23]
Hello,

I discovered today in the latest update the function that interested me a lot: a button to close the notification.

I have just one question, is it possible to have the close button in the top right small, to keep the cover in large ?

Like this :
![notifications](https://cloud.githubusercontent.com/assets/12293195/11962040/06993004-a8dd-11e5-9c92-145ef4849968.jpg)

Thank you.

Vincent

**Comment by homerours** [comment]
I search for that in the android SDK. The only thing I found that could show a close button on the top right is the [setShowCancelButton method](http://developer.android.com/reference/android/support/v7/app/NotificationCompat.MediaStyle.html#setShowCancelButton(boolean)).
However, this method is only (as far as I searched...) available through the "Android Support librairies" ([some infos here](http://martiancraft.com/blog/2015/06/android-support-library/))... Even in the latest SDK release, I don't find this method...

**Comment by alisonmonteiro** [comment]
Hey, @lesonunique

I've set "hasClose" flag to "true" and my notification looks like

![img_20160122_145550](https://cloud.githubusercontent.com/assets/3016692/12518635/7b8eb25a-c118-11e5-802c-439ca0b0bc7a.jpg)

**Comment by 0505gonzalez** [comment]
This seems to be referring to customizing the notification style, which is covered by issue https://github.com/homerours/cordova-music-controls-plugin/issues/33
