### ISSUE TITLE
Android 4.1 + does not work notification

### ISSUE THREAD

**Issue by aykutc** [homerours/cordova-music-controls-plugin#25]
I check this plugin android 4.1.2 and 4.2.2 but it does not work,
it only work android 5.
I see this error on logcat.
Do you have a solution ?

`01-27 23:21:56.568 26101-26101/com.ionicframework.example403106 W/dalvikvm: VFY: unable to resolve virtual method 137: Landroid/media/AudioManager;.registerMediaButtonEventReceiver (Landroid/app/PendingIntent;)V
01-27 23:21:56.568 26101-26101/com.ionicframework.example403106 W/dalvikvm: VFY: unable to resolve virtual method 139: Landroid/media/AudioManager;.unregisterMediaButtonEventReceiver (Landroid/app/PendingIntent;)V
01-27 23:21:56.578 26101-26101/com.ionicframework.example403106 W/System.err: java.lang.NoSuchMethodError: android.media.AudioManager.registerMediaButtonEventReceiver
01-27 23:21:56.578 26101-26101/com.ionicframework.example403106 W/System.err:     at com.homerours.musiccontrols.MusicControls.registerMediaButtonEvent(MusicControls.java:50)
01-27 23:21:56.578 26101-26101/com.ionicframework.example403106 W/System.err:     at com.homerours.musiccontrols.MusicControls.initialize(MusicControls.java:75)
01-27 23:21:56.578 26101-26101/com.ionicframework.example403106 W/System.err:     at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:56)
01-27 23:21:56.583 26101-26101/com.ionicframework.example403106 W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
01-27 23:21:56.583 26101-26101/com.ionicframework.example403106 W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
01-27 23:21:56.583 26101-26101/com.ionicframework.example403106 W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
01-27 23:21:56.583 26101-26101/com.ionicframework.example403106 W/System.err:     at org.apache.cordova.CordovaBridge.promptOnJsPrompt(CordovaBridge.java:135)
01-27 23:21:56.583 26101-26101/com.ionicframework.example403106 W/System.err:     at org.apache.cordova.engine.SystemWebChromeClient.onJsPrompt(SystemWebChromeClient.java:124)
01-27 23:21:56.583 26101-26101/com.ionicframework.example403106 W/System.err:     at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java)
01-27 23:21:56.583 26101-26101/com.ionicframework.example403106 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java)
01-27 23:21:56.583 26101-26101/com.ionicframework.example403106 W/System.err:     at android.os.Looper.loop(Looper.java)
01-27 23:21:56.588 26101-26101/com.ionicframework.example403106 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java)
01-27 23:21:56.588 26101-26101/com.ionicframework.example403106 W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
01-27 23:21:56.588 26101-26101/com.ionicframework.example403106 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
01-27 23:21:56.588 26101-26101/com.ionicframework.example403106 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
01-27 23:21:56.588 26101-26101/com.ionicframework.example403106 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
01-27 23:21:56.588 26101-26101/com.ionicframework.example403106 W/System.err:     at dalvik.system.NativeStart.main(Native Method)
01-27 23:21:56.598 26101-26101/com.ionicframework.example403106 W/System.err: java.lang.NoSuchMethodError: android.media.AudioManager.registerMediaButtonEventReceiver
01-27 23:21:56.598 26101-26101/com.ionicframework.example403106 W/System.err:     at com.homerours.musiccontrols.MusicControls.registerMediaButtonEvent(MusicControls.java:50)
01-27 23:21:56.598 26101-26101/com.ionicframework.example403106 W/System.err:     at com.homerours.musiccontrols.MusicControls.initialize(MusicControls.java:75)
01-27 23:21:56.598 26101-26101/com.ionicframework.example403106 W/System.err:     at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:56)
01-27 23:21:56.598 26101-26101/com.ionicframework.example403106 W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
01-27 23:21:56.603 26101-26101/com.ionicframework.example403106 W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
01-27 23:21:56.603 26101-26101/com.ionicframework.example403106 W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
01-27 23:21:56.603 26101-26101/com.ionicframework.example403106 W/System.err:     at org.apache.cordova.CordovaBridge.promptOnJsPrompt(CordovaBridge.java:135)
01-27 23:21:56.603 26101-26101/com.ionicframework.example403106 W/System.err:     at org.apache.cordova.engine.SystemWebChromeClient.onJsPrompt(SystemWebChromeClient.java:124)
01-27 23:21:56.603 26101-26101/com.ionicframework.example403106 W/System.err:     at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java)
01-27 23:21:56.603 26101-26101/com.ionicframework.example403106 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java)
01-27 23:21:56.603 26101-26101/com.ionicframework.example403106 W/System.err:     at android.os.Looper.loop(Looper.java)
01-27 23:21:56.603 26101-26101/com.ionicframework.example403106 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java)
01-27 23:21:56.603 26101-26101/com.ionicframework.example403106 W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
01-27 23:21:56.608 26101-26101/com.ionicframework.example403106 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
01-27 23:21:56.608 26101-26101/com.ionicframework.example403106 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
01-27 23:21:56.608 26101-26101/com.ionicframework.example403106 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
01-27 23:21:56.608 26101-26101/com.ionicframework.example403106 W/System.err:     at dalvik.system.NativeStart.main(Native Method)`

**Comment by aykutc** [comment]
Sorry, I solve this errors, You should announce that registerMediaButtonEvent require minimum android 4.4 therefore ;
People who use this plugin should delete some line in  MusicControls.java:
These lines:
		this.mAudioManager.registerMediaButtonEventReceiver(this.mediaButtonPendingIntent);
		this.mAudioManager.unregisterMediaButtonEventReceiver(this.mediaButtonPendingIntent);

**Comment by homerours** [comment]
Thank you for reporting this issue and resolving it! It just escaped this lines "programmaticaly": 725fed36 It should now work without having to comment anything.
