### ISSUE TITLE
Doesn't work on LG V10, Android 5.1.1

### ISSUE THREAD

**Issue by schmoofer** [homerours/cordova-music-controls-plugin#28]
Lockscreen controls and metadata do not appear on an LG V10 running Android 5.1.1. Used the same code successfully on a Nexus 7 also running Android 5.1.1.

**Comment by homerours** [comment]
Did you try this : https://github.com/homerours/cordova-music-controls-plugin/issues/20 ?

**Comment by schmoofer** [comment]
Perfect, that fixed it.

**Comment by homerours** [comment]
I have updated the plugin: 2722bd1fbe9
It should now work on your LG phone, without having to remove "manually" any line. Tell me if it works for you!

**Comment by schmoofer** [comment]
Yep, works like a charm. Thanks!
