### ISSUE TITLE
Local image asset isn't found

### ISSUE THREAD

**Issue by ds8k** [homerours/cordova-music-controls-plugin#29]
When passing in an image file that exists locally within the app Android is unable to find the file:
```
window.MusicControls.create({
                    track: 'Title',
                    artist: 'Artist',
                    cover: 'img/logo.jpg',
                    isPlaying: false,
                    dismissable: true,
                    hasPrev: false,
                    hasNext: false,
                    hasClose: true
                });
```

```
03-03 15:40:38.771 31274 31290 W System.err: java.io.FileNotFoundException: img/logo.jpg: open failed: ENOENT (No such file or directory)
```

On a OnePlus One running Android 6.0.1

**Comment by homerours** [comment]
The 'cover' attribute should be an absolute path. If you are using [cordova file plugin](https://github.com/apache/cordova-plugin-file), you can use `cordova.file.applicationDirectory` or `cordova.file.externalApplicationStorageDirectory` do build the full path.

**Comment by ds8k** [comment]
And if I'm not using the file plugin?

**Comment by ds8k** [comment]
Instead of
```
Uri uri = Uri.parse(localURL);
File file = new File(uri.getPath());
FileInputStream fileStream = new FileInputStream(file);
BufferedInputStream buf = new BufferedInputStream(fileStream);
```

I made the following change
```
InputStream fileStream = cordovaActivity.getAssets().open("www/" + uri);
BufferedInputStream buf = new BufferedInputStream(fileStream);
```

and now the image loads fine with no errors. Having said that, I'm NOT great at Java and have no idea if this would cause issues.

**Comment by homerours** [comment]
You are totally right! 
I commited the changes, it should work now.

**Comment by ds8k** [comment]
Sweet! That I could help out.
