### ISSUE TITLE
Cover from local file

### ISSUE THREAD

**Issue by ghenry22** [homerours/cordova-music-controls-plugin#30]
Seeing some issues using local files for covers.  If I change to a http:// url to load the image and it works fine and uses the image.  If I place a file called absolution.jpg in /albums or even just in the www root and try to load it as per the documentation it is never used and no error is logged to the console.

cover: 'albums/absolution.jpg'
image is not used

cover: 'absolution.jpg'
cover is not used

https://remote.server.com/absolution.jpg
cover IS used.

**Comment by ghenry22** [comment]
Testing on Samsung Galaxy S6 with android 5.1.1

Using latest Cordova Android 5.1.1 platform and latest plugin code installed by git

**Comment by homerours** [comment]
I just tried exactly the same settings (Cordova 6.0.0, Cordova Android 5.1.1) on genymotion emulator and the image WAS used...

**Comment by ghenry22** [comment]
It works fine with a full file:// path.  But any relative path to the www/ root is a no go.  Tried it on another device.  Same thing.  I am running Android OS 5.1.1, cordova android platform 5.1.1, cordova 6.0.0.

Tried it on a LG G4 and my usual Samsung S6 test device and got the same behaviour.

I have worked around it by using the full path with file:// prefix for my case.

**Comment by ghenry22** [comment]
adding support for cdvfile:// urls might be something to consider as well since all the core cordova plugins support this now and makes it simple and cross platform.

**Comment by ghenry22** [comment]
I guess the solution is just to use a full file:// path, I have that in my current app and it works fine with local files so I'll just close this issue.
