### ISSUE TITLE
[Android] lock screen image

### ISSUE THREAD

**Issue by cinder92** [homerours/cordova-music-controls-plugin#34]
Hi! is there any way to put an image of current song in lock screen? like spotify does? it will be great!

**Comment by djmMax** [comment]
Look https://github.com/wnyc/cordova-plugin-playerhater

**Comment by cinder92** [comment]
@djmMax  but this is only on ios is not?

**Comment by djmMax** [comment]
No it works well on iOS and Android. But it not update for lastest android version

**Comment by cinder92** [comment]
do you have any example on android with lock screen? :D

**Comment by djmMax** [comment]
No i try this but I could not compile for android 16. finally I use cordova-music-controls-plugin whitout LockScreen :cry:

**Comment by cinder92** [comment]
ok, i will try it :+1:

**Comment by djmMax** [comment]
@cinder92 please notify me!

**Comment by ghenry22** [comment]
this plugin does display the specified image and music controls on the lock screen widget

**Comment by 0505gonzalez** [comment]
Closing as it seems ghenry22 confirmed it worked.
