### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by igor9silva** [homerours/cordova-music-controls-plugin#36]
Hi,

As it's a best pratice, It'd be nice to have release tags (e.g. v1.3.0) for each new version. This way it's possible to point at that very specific version in automation tools (e.g. npm, bower, jenkins), avoiding breaking anything when there is a new release.

**Comment by sinedied** [comment]
In the meantime, you can just use the commit hash to have the same behavior, ie:
```
cordova plugin add <repo>.git#<commit_hash>
```

**Comment by 0505gonzalez** [comment]
Good point. We'll start tagging with the most recent version, 1.4.0
