### ISSUE TITLE
MusicControls is not defined

### ISSUE THREAD

**Issue by asepshogun** [homerours/cordova-music-controls-plugin#39]
heloo, i have question.
i use this plugin and there's an error "Uncaught ReferenceError: MusicControls is not defined"
can someone told me why ?

**Comment by 0505gonzalez** [comment]
Hello, please make sure you have installed the plugin correctly for the platform you are testing on. Unfortunately it's hard to help any more without context.

**Comment by 0505gonzalez** [comment]
https://github.com/homerours/cordova-music-controls-plugin/issues/17
