### ISSUE TITLE
MusicControls pause and play icon and fuctionality is not toggled.

### ISSUE THREAD

**Issue by naitikpatel1990** [homerours/cordova-music-controls-plugin#42]
i tested in android only yet, 

In MusicControls updateIsPlaying( panel only pause is showing as icon ) , is it possible to do like normal player pause and play toggle icon as well as event.?

right now i can see only pause icon and even if i clicked many time it's calling pause audio event only,

even if i tried `MusicControls.updateIsPlaying(true);`  still only pause audio not playing again and not even update icon for play/pause toggle.
I am using android 6.0.1

Please help

**Comment by NikolaBalaban** [comment]
I think that this is not explained properly so I'll try to help:

Add `MusicControls.updateIsPlaying(true);` in **// Do something** section:
`case 'music-controls-play':`
`          // Do something`
`          break;`

Also, add `MusicControls.updateIsPlaying(false);` in:
`case 'music-controls-pause':`
`          // Do something`
`          break;`

So you will end up with something like: 
`case 'music-controls-play':`
`         MusicControls.updateIsPlaying(true);`
`          break;`
`case 'music-controls-pause':`
`          MusicControls.updateIsPlaying(false);`
`          break;`

Now it should work. Works fine for me. Also, check if you have latest version (1.4.0) of this plugin. 

latest version instalation: 
**cordova plugin add https://github.com/homerours/cordova-music-controls-plugin**

**Comment by 0505gonzalez** [comment]
Closing as it seems like a solution was provided.
