### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by Juanperezc** [homerours/cordova-music-controls-plugin#44]
I have a problem the plugin does not work on my android device I did all the steps, I downloaded the git through the console. I added the plugin to config.xml then create a js with the following code

```
`MusicControls.create({
    track       : 'Time is Running Out',        // optional, default : ''
      artist      : 'Muse',                     // optional, default : ''
    cover       : '',      // optional, default : nothing
    // cover can be a local path (use fullpath 'file:///storage/emulated/...', or only 'my_image.jpg' if my_image.jpg is in the www folder of your app)
    //           or a remote url ('http://...', 'https://...', 'ftp://...')
  isPlaying   : true,                           // optional, default : true
    dismissable : true,                         // optional, default : false

    // hide previous/next/close buttons:
    hasPrev   : false,      // show previous button, optional, default: true
    hasNext   : false,      // show next button, optional, default: true
    hasClose  : true,       // show close button, optional, default: false

  // iOS only, optional
  album       : 'Absolution',     // optional, default: ''
  duration : 60, // optional, default: 0
  elapsed : 10, // optional, default: 0

    // Android only, optional
    // text displayed in the status bar when the notification (and the ticker) are updated
    ticker    : 'Now playing "Time is Running Out"'
}, onSuccess, onError);`

```
And call it in the index.html
` <script type="text/javascript" src="js/music-control.js"></script>`

But nothing appears on the notification bar

I also use the code on the play buttons but nothing like that does not work

`MusicControls.updateIsPlaying(true);`

**Comment by GerardoLSJ** [comment]
Try with this small template, It download a song pops an Alert and then you can push the "Play button"

https://github.com/GerardoLSJ/cordova-download-template-to-private-directory

I tested in 4 android devices, 4.1.2, 5.1, and two 6.0 and worked in all of them

**Comment by Juanperezc** [comment]
I solved the problem, apparently it was not running the event MusicControls.create, have to run an audio before it appears?

**Comment by GerardoLSJ** [comment]
I don't know why but it appears so, I try with an <audio> tag and the audio.play() (Avoiding the Media plugin) and it works with a little delay
