### ISSUE TITLE
Local Artwork not working anymore

### ISSUE THREAD

**Issue by dermansi** [homerours/cordova-music-controls-plugin#46]
My local cover in www folder doesnt't show up

**Comment by 0505gonzalez** [comment]
Can you provide more details? Platform, OS version, plugin version, any other pertinent details.

**Comment by dermansi** [comment]
I had to run 'ionic state reset' which installs all platforms and plugins again. It stopped working after that.
Manually reinstalling the platform or plugin did not work, too.

Noticed on Android 5.1 and Android 6.0.1

Adding a remote image still works.

**Comment by dermansi** [comment]
It worked again after updating to 1.4. (Even tho i manually updated to 1.4 before and it didn't fix it).
Closed for now.
