### ISSUE TITLE
How to create in Ionic 2

### ISSUE THREAD

**Issue by tordnilsen** [homerours/cordova-music-controls-plugin#47]
Hi!
Thanks for this plug-in (I think)
I can't get it to work in my Ionic 2 project. It has probably nothing to do with the plugin it self.
In my ts I have:
 import {MusicControls} from 'ionic-native';
//--
showMusicControls = function(){
    MusicControls.create({
        track       : 'Time is Running Out',        // optional, default : ''
          artist      : 'Muse',                     // optional, default : ''
        cover       : 'albums/absolution.jpg',      // optional, default : nothing
    }, onSuccess, onError);

};

But I get three errors: 
Cannot find name 'onSuccess'.at line
Cannot find name 'onError'.at line
Supplied parameters do not match any signature of call target.at line 

Can you please show how to create Musiccontrols in Ionic 2?

**Comment by dermansi** [comment]
You have to create onSuccess() and onError() on your own or simply delete them.

**Comment by tordnilsen** [comment]
Thanks for amazingly fast respons!!
My ts looks now like this:
	showMusicControls = function(){
   MusicControls.create({
       track       : 'Time is Running Out',        // optional, default : ''
         artist      : 'Muse',                     // optional, default : ''
       cover       : 'albums/absolution.jpg'      // optional, default : nothing
   });
};

And now I got:
Argument of type '{ track: string; artist: string; cover: string; }' is not assignable to parameter of type 'MusicControlsOptions'.

**Comment by tordnilsen** [comment]
I got it to work!! Thanks
I though that because some of the parameters is optional I didn't have to implement them. So when I 
have all parameters with (as described) it works. 
Thanks!!!
