### ISSUE TITLE
Can we have updateDismissable(boolean) added

### ISSUE THREAD

**Issue by neoassyrian** [homerours/cordova-music-controls-plugin#49]
Hi guys, 
Can we have a method to update the "dismissable" property of the notification without re-creating the whole control? Would like to be able to update this when the media is playing/pausing. 

Should be similar to updateIsPlaying(boolean)

**Comment by dermansi** [comment]
Can you bump npm version again please?

**Comment by homerours** [comment]
@neoassyrian Thanks for the PR :+1: 

@dermansi done !
