### ISSUE TITLE
Handle earphone buttons

### ISSUE THREAD

**Issue by filfat** [homerours/cordova-music-controls-plugin#6]
Most earphones comes with at least one button (1 for pause/play, 2 for next, 3 for previous) or three buttons. Having support for that would be great.

Cheers.

**Comment by homerours** [comment]
I'm going to add support for that on android.

**Comment by homerours** [comment]
I added support for play/pause: 6c26f0be2c9fcc3cf6f48e4a4b4e687c3fee5676

**Comment by CoDEmanX** [comment]
Could you also add double-press support? Clicking twice the earphone button should skip to the next track.

**Comment by homerours** [comment]
It doesn't "really" support double-press event: if you double-press the earphone button, it will fire the 'music-controls-headset-button' twice. From that, you can count the number of press within a time lapse (that you choose) and decide (on your own) if correspond to a double (or triple) press.

**Comment by CoDEmanX** [comment]
I see, so it really just forwards the press event, and I need to roll my own code to pause, resume or whatever.

I assume I can setTimeout() in JS on the first press with a timeout around 0.5 seconds, which will play/pause the medium. If a second press occurs, I will have to check for a pending timeout and abort it, then skip to the next medium.

**Comment by homerours** [comment]
Yes, exactly !
