### ISSUE TITLE
iOS: notifications/lock-screen time elapsed issue

### ISSUE THREAD

**Issue by AshishMehra** [homerours/cordova-music-controls-plugin#60]
Hey everyone,

The elapsed time on the iOS controls keep goes out of sync. Everytime you hit pause it goes back to zero. I've seen other apps using this plugin and they too have simply ignored sending time information to the plugin, which works fine in the notifications area (as iOS hides the time bar) but in the lockscreen it shows an ugly empty time bar.

Is there a way to fix this functionality? If not then is there a way to hide the time bar on the lockscreen?

Your help would be greatly appreciated.

(Angular 1.5, Ionic 1.3.2)

Cheers!

**Comment by BuddyLReno** [comment]
I've created a PR to fix this. #71
