### ISSUE TITLE
[BUG] Controls stop responding after one action

### ISSUE THREAD

**Issue by filfat** [homerours/cordova-music-controls-plugin#7]
Alright here's what I did
```javascript
//Above: add data to MusicControls
if (typeof MusicControls !== 'undefined') {
    function x (s) {
        if (s === 'music-controls-next') {
            alert('next');
        } else if (s === 'music-controls-previous') {
            alert('prev');
        } else if (s === 'music-controls-pause') {
            alert('pause');
        } else if (s === 'music-controls-play') {
            alert('play');
        }
    }
    MusicControls.listen(x, ...);
}
```
The above code only works once then stops working.

Cheers.

**Comment by homerours** [comment]
You have to fire the listen function after each action. 
A solution could be to save a user callback function in the MusicController JS object. Every time that this MusicController object gets a callback from native, it runs this function and reload the listening operation from itself. It would therefore avoid the user to do it himself.
