### ISSUE TITLE
Update Title, Cover and Artist

### ISSUE THREAD

**Issue by RBrenet** [homerours/cordova-music-controls-plugin#74]
Hello and sorry for my stupid question, but what method we need to use to update Artist, Cover and Title?

Thank you in advance.

**Comment by homerours** [comment]
Hello! You just have to use the "create" method. This will replace the previous notification by a new one.

**Comment by romain25** [comment]
Thanks application dont crash when you create 10000 MusicControl ?

**Comment by romain25** [comment]
Or you need to destroy before create ?

**Comment by RBrenet** [comment]
Ok, I Close this issue it's work like a charm on Android and iOS, I have refresh 1000 times without problem and crash.
Thanks for your beautiful plugin.
