### ISSUE TITLE
Previous and next buttons not showing up

### ISSUE THREAD

**Issue by CodeBitt** [homerours/cordova-music-controls-plugin#86]
The previous and next buttons are not showing up on my Android. Yes, I do have them set to `true` in the options.

**Comment by CVeniamin** [comment]
I think this issue also is solved with #83

**Comment by CodeBitt** [comment]
No, neither the fast forward nor the next button show up when I have `hasPrev` and `hasNext` set to `true`

**Comment by CodeBitt** [comment]
Darn, I forgot to run webpack again! It works fine now.
