### ISSUE TITLE
Cordova plugin add Error

### ISSUE THREAD

**Issue by versustune** [homerours/cordova-music-controls-plugin#87]
Hi,
I dont can't install this plugin with the error message:
```
Error: Failed to fetch plugin https://github.com/homerours/cordova-music-controls-plugin via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

**Comment by CodeBitt** [comment]
This is an error with cordova

**Comment by versustune** [comment]
I do not use it anymore

**Comment by baalpeteor** [comment]
> I do not use it anymore

what did you use instead? I need something to put the icons in the tray for a radio stream (to stop and pause). seems no one is fixing bugs, updating this app nomore and is probably dead. I have a message/ticket out on this, another guy as well months earlier and no fix or response

**Comment by versustune** [comment]
@baalpeteor now i code my apps native

**Comment by owen-m1** [comment]
@baalpeteor Use phonegap
